app/ig/routes.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from app.apiauthhelper import token_required


ig = Blueprint('ig', __name__, template_folder='ig_templates')

from .forms import CreatePostForm, UpdatePostForm
from app.models import db, Post, User


@ig.route('/posts')
def posts():
    posts = Post.query.all()[::-1] # query comes from SQAlchemy. This specific query gets all of the existing posts from our Post model database and sorts them in reverse order [::-1] because we want the newest on top
    return render_template('posts.html', posts = posts)

@ig.route('/create-post', methods=["GET", "POST"])
@login_required # login_required is a built-in
def createPost():
    form = CreatePostForm()
    if request.method == "POST":
        if form.validate():
            title = form.title.data
            img_url = form.img_url.data
            caption = form.caption.data

            # Creating a Post instance. The parameters need to match up with how you created the model
            post = Post(title, img_url, caption, current_user.id) # current_user is a global variable we have access to because of LoginManager in our __init__.py, but we still have to import current user 

            db.session.add(post)
            db.session.commit()   

            return redirect(url_for('home'))         

    return render_template('createpost.html', form = form)

@ig.route('/posts/<int:post_id>') # <> creates a variable. The type of variable has to be specified, so we specified it as int:
def individualPost(post_id): # because we are getting a variable, we need to accept it in our function
    post = Post.query.filter_by(id=post_id).first() # filter_by comes from a Flask query command. post_id is what's being passed in, and id is the name of the column
    if post is None:
        return redirect(url_for('ig.posts'))
    return render_template('individual_post.html', post = post)

@ig.route('/posts/update/<int:post_id>', methods=["GET","POST"]) # you GET the website and you UPDATE (POST) the information
@login_required
def updatePost(post_id):
    post = Post.query.filter_by(id=post_id).first()
    if post is None:
        return redirect(url_for('ig.posts'))
    if post.user_id != current_user.id:
        return redirect(url_for('ig.posts'))
    form = UpdatePostForm()
    if request.method == "POST":
        if form.validate():
            title = form.title.data
            img_url = form.img_url.data
            caption = form.caption.data

            # update the original post (as opposed to creating a new one like in createPost)
            post.title = title
            post.image = img_url
            post.caption = caption

            # Also no longer need to 'add' to database, like in createPost. Instead you just commit it

            db.session.commit()   

            return redirect(url_for('home'))         
    return render_template('updatepost.html', form=form, post = post)


@ig.route('/posts/delete/<int:post_id>', methods=["POST"]) # not a GET request because you are really just POSTing to delete
@login_required
def deletePost(post_id):
    post = Post.query.filter_by(id=post_id).first()
    if post is None:
        return redirect(url_for('ig.posts'))
    if post.user_id != current_user.id:
        return redirect(url_for('ig.posts'))

    db.session.delete(post)
    db.session.commit()
               
    return redirect(url_for('ig.posts'))


# 
# 
#   API STARTS HERE
# 
#

@ig.route('/api/posts')
def apiPosts():
    posts = Post.query.all()[::-1]
    return {
        'status': 'ok',
        'total_results': len(posts),
        'posts': [p.to_dict() for p in posts]
        }

@ig.route('/api/posts/<int:post_id>')
def apiSinglePost(post_id):
    post = Post.query.filter_by(id=post_id).first()
    if post is None:
        return {
            'status': 'not ok',
            'total_results': 0,
        }
    return {
        'status': 'ok',
        'total_results': 1,
        'post': post.to_dict()
        }


@ig.route('/api/create-post', methods=["POST"])
@token_required
def apiCreatePost(user):
    data = request.json

    title = data['title']
    img_url = data['img_url']
    caption = data['caption']

    post = Post(title, img_url, caption, user.id)

    db.session.add(post)
    db.session.commit()   

    return {
        'status': 'ok',
        'message': 'Successfully create a new post.',
        'post': post.to_dict()
    }

app/pokemon/routes.py
from flask import Blueprint, redirect, render_template, request, url_for
import requests as r

pokemon = Blueprint('pokemon', __name__, template_folder="pokemon_templates")


@pokemon.route('/pokemon', methods=["POST"])
def myPokemon():
    name = request.form.to_dict()['name']
    data = r.get(f"https://pokeapi.co/api/v2/pokemon/{name}")
    if data.status_code == 200: # status code 200 means success
        my_data = data.json()
        abilities = my_data['abilities']
        my_abilities = []
        for item in abilities:
            my_abilities.append((item['ability']['name']))
        my_img = my_data['sprites']['front_default']
        return render_template('pokemon.html', abilities=my_abilities, img_url=my_img, name=name)
    return redirect(url_for('home'))

app/shop/routes.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import current_user, login_required

#
#
# BASED ON IG ROUTES.PY (everything besides showCart and the admin createProduct routes)
#
#


shop = Blueprint('shop', __name__, template_folder='shop_templates')

from app.models import db, Product, Cart
from .forms import CreateProductForm

@shop.route('/products')
@login_required
def allProducts():
    products = Product.query.all()
    return render_template('shop.html', products=products)

@shop.route('/products/<int:product_id>')
@login_required
def individualProduct(product_id):
    product = Product.query.filter_by(id=product_id).first()
    if product is None:
        return redirect(url_for('shop.allProducts'))
    return render_template('individual_product.html', product = product)

# CART FUNCTIONALITY
@shop.route('/cart')
@login_required
def showCart():
    cart = Cart.query.filter_by(user_id=current_user.id)
    count = {}
    for item in cart:
        count[item.product_id] = count.get(item.product_id, 0) + 1 # counting with the .get method
    
    cart_products = []
    for product_id in count:
        product_info = Product.query.filter_by(id=product_id).first().to_dict()
        product_info["quantity"] = count[product_id]
        product_info['subtotal'] = product_info['quantity'] * product_info['price']
        cart_products.append(product_info)

    return render_template('show_cart.html', cart = cart_products)


@shop.route('/cart/add/<int:product_id>')
def addToCart(product_id):
    cart_item = Cart(current_user.id, product_id)
    db.session.add(cart_item)
    db.session.commit()
    return redirect(url_for('shop.allProducts'))

@shop.route('/cart/add', methods=["POST"])
def addToCart2():
    product_id = request.form.to_dict()['product_id']
    cart_item = Cart(current_user.id, product_id)
    db.session.add(cart_item)
    db.session.commit()
    return redirect(url_for('shop.individualProduct', product_id=product_id))



# ADMIN CREATE PRODUCT PAGE
@shop.route('/products/create')
@login_required
def createProduct():
    if current_user.is_admin:
        form = CreateProductForm()
        if request.method == "POST":
            if form.validate():
                product_name = form.product_name.data
                img_url = form.img_url.data
                description = form.description.data
                price = form.price.data

                product = Product(product_name, img_url, description, price)

                db.session.add(product)
                db.session.commit()   

                return redirect(url_for('shop.createProduct'))         

        return render_template('create_product.html', form = form)
    else:
        return redirect(url_for('shop.allProducts'))   




# 
#  
# API ROUTES
# 
# 
#  
from app.apiauthhelper import token_required

@shop.route('/api/products')
def apiProducts():
    products = Product.query.all()
    return {
        "status": "ok",
        "total_results": len(products),
        'products': [p.to_dict() for p in products]
    }

@shop.route('/api/products/<int:product_id>')
def apiSingleProduct(product_id):
    product = Product.query.filter_by(id=product_id).first()
    if product is None:
        return {
            'status': 'not ok',
            'total_results': 0,
        }
    return {
        'status': 'ok',
        'total_results': 1,
        'product': product.to_dict()
        }


@shop.route('/api/cart/get')
@token_required
def getCartAPI(user):
    cart = Cart.query.filter_by(user_id=user.id)
    myCart = [Product.query.filter_by(id=item.product_id).first().to_dict() for item in cart]
    return {
        'status': 'ok',
        'cart': myCart
    }

@shop.route('/api/cart/add', methods=["POST"])
@token_required
def addToCartAPI(user):
    data = request.json

    product_id = data['product_id']

    newCartItem = Cart(user.id, product_id)
    
    db.session.add(newCartItem)
    db.session.commit()

    return {
        'status': 'ok',
        'message': "Successfully added item to cart!"
    }

@shop.route('/api/cart/remove', methods=["POST"])
@token_required
def removeFromCartAPI(user):
    data = request.json
    
    product_id = data['product_id']

    cartItem = Cart.query.filter_by(user_id=user.id).filter_by(product_id=product_id).first()

    if cartItem:
        db.session.delete(cartItem)
        db.session.commit()
        return {
            'status': 'ok',
            'message': "Successfully removed item from cart."
        }
    return {
        'status': 'not ok',
        'message': 'That item does not exists in your cart.'
    }

import stripe
import os
stripe.api_key = os.environ.get('STRIPE_SECRET_KEY')

@shop.route('/api/stripe/create-checkout-session', methods=["POST"])
def createCheckoutSession():
    try:
        checkout_session = stripe.checkout.Session.create(
            line_items=[
                {
                    # Provide the exact Price ID (for example, pr_1234) of the product you want to sell
                    'price': 'price_1JpbJLDTfh3G5wtDtecdGTdJ',
                    'quantity': 1,
                },
            ],
            mode='subscription',
            success_url='http://localhost:3000/' + '?success=true',
            cancel_url='http://localhost:3000/stripe/shop' + '?canceled=true',
        )

    except Exception as e:
        return str(e)

    return redirect(checkout_session.url, code=303)

app/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h2>This is the about page</h2>


{% endblock content %}




    

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}"> <!-- using a jinja function instead of navigating directly to the file, because when you host your project on the internet, the host will have a different structure -->
    
</head>
<body>
    {% include 'navbar.html' %} <!-- include is a built in jinja function to render the html file being called -->

    <main class="container">
        {% with messages = get_flashed_messages(with_categories=True) %} <!-- Allows flash messages on any of our html pages -->
            {% if messages %} <!-- only if there are messages to display-->
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %} <!-- every jinja for loop needs an endfor -->
            {% endif %} <!-- every jinja if statement needs an endif -->
        {% endwith %} <!-- every jinja with messages needs an endwith -->

        {% block content %} <!-- All of our other html files will have an "extends base", which loads up base.html, so their block content will be inserted here -->



        {% endblock content %} <!-- every jinja block content needs an endblock content -->
    </main>




    <script src="https://kit.fontawesome.com/3d81577920.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

app/templates/index.html
<!-- 
-
-
- SEE NAVBAR.HTML AND BASE.HTML FOR MORE JINJA NOTES
-
-
 -->



{% extends 'base.html' %}

{% block content %}
    <h1>Hello World</h1>
    <ul>
        <!-- We have access to the variable my_list because we passed it into the render_template() function as an argument to access in this html file -->
        {% for name in my_list %} <!-- we could have called name anything here, just like in other for loops, but we called it name to be clear about what we're getting back while we go through the loop -->
            {% if name == "Shoha" %}
                <li><b>{{ name }}</b></li>
            {% else %}
                <li>{{ name }}</li>
            {% endif %}
        {% endfor %}


    </ul>


{% endblock content %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('home') }}">Home</a> <!-- url_for() is a jinja function that takes in the name of a function and returns the url for that function, but for home, we could have also just used href="/" which represents the home page -->
                    <!-- We are using url_for to have the option to create dynamic routes, where the last thing in the url path is a variable that can change -->
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('shop.allProducts') }}">Shop</a>
                </li>
                <!-- current_user is a global variable we have access to because of LoginManager in __init__ and .is_authenticated is an attribute that comes with current_user -->
                {% if current_user.is_authenticated %} <!-- % % inside curly braces is for expressions (like a command), double curly braces is for a variable -->
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('ig.createPost') }}">Create Post</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logMeOut') }}">Log Out</a>
                </li>

                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logMeIn') }}">Sign In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signMeUp') }}">Sign Up</a>
                </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">{{ current_user.username }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('shop.showCart') }}" tabindex="-1" aria-disabled="true"><i class="fas fa-shopping-cart"></i></a>
                </li>
            </ul>
            <form class="d-flex" action="{{ url_for('pokemon.myPokemon') }}" method="POST">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="name">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>